spring:
  application:
    name: dolphin-boot-mall
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

# 应用服务 WEB 访问端口
server:
  port: 8080
# Actuator Web 访问端口
management:
  server:
    port: 8081

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml